site_name: AOE Wiki
site_url: https://teamaof.github.io/AOE-Wiki/
repo_url: https://github.com/TeamAOF/AOE-Wiki
repo_name: AOE Wiki on GitHub
edit_uri: blob/wiki/docs/
theme:
  name: material
  logo: img/EOA_logoB.png
  favicon: img/eoa_fav.ico
  icon:
    repo: fontawesome/brands/github

  font:
    text: Finlandica

  features:
    - content.action.view
    - content.action.edit
    - navigation.path
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - search.suggest
    - search.highlight
    - search.share

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: aoe-light
      #      primary: indigo
      #      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: aoe-dark
      #      primary: red
      #      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - footnotes
  - admonition
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.blocks.caption
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: false
  - toc:
      permalink: true

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: TeamAOF/AOE-Wiki
      branch: wiki
  - glightbox:
      skip_classes:
        - skip-lightbox
  - search

copyright: Copyright &copy; 2025 Team AOE

nav:
  - Home: index.md
  - Craftoria Tips & Tricks: 
      - Resouce Generation: Craftoriatips\Resouce Generate.md
  - Mod Packs:
      - Craftoria: modpacks/Craftoria.md
      #      - FAQ: modpacks/Craftoria/faq.md
      #      - Hype: modpacks/Craftoria/media.md
      - All of Fabric 7: modpacks/aof7.md
      - All of Fabric 6: modpacks/aof6.md
      - All of Fabric 5: modpacks/aof5.md
      - All of Fabric 4: modpacks/aof4.md
      - All of Fabric 3: modpacks/aof3.md
  - Servers:
      - Official Servers: servers/official_servers.md
      - Your Own Server: servers/server.md
      - Sharing: servers/sharing.md
  - Launchers:
      - CurseForge: launchers/curseforge.md
      - Prism Launcher: launchers/prism.md
  - Java & Performance: performance.md
  - Trouble Shooting: crashing.md
  - Select Mods:
      - EMI: mods/emi.md
      #    - Just Dire Things: mods/jdt.md
      - Ars Nouveau: mods/ars.md
      - Modern Industrialization: mods/mi.md
  - FAQs: faqs.md
